### ISSUE TITLE
Shut down Motor on host dropping serial connection

### ISSUE THREAD

**Issue by dctsystems** [pimoroni/flotilla-python#5]
Feature request?

When a program quits the flotilla dock simply stops, and does nothing. However if motors are running they keep running, which is potentially a bad idea. While the host program can (should) stop the motors if it exits cleanly, if it crashes or is killed then cleanup might not happen.

Could the dock firmware be updated to detect that the serial connection has been dropped, and make it fail-safe? This would primarily apply to motors, but would also be good for rainbow

**Comment by Gadgetoid** [comment]
I'm not sure if we can detect a serial connection drop since there are many factors at play, but it's worth investigating.

If you want a real mind-bender, run a motor, kill the program sending it commands, then unplug it and plug it back in again.

Baffled? No? Find a USB power adaptor and plug it into that.
